version: '2.1'
services:
  apache:
    build: apache/.
    image: rakesh635/apachedemo
    restart: always
    ports:
      - 80:80
      
  catalog:
    build: microservice-kubernetes-demo-catalog/.
    image: rakesh635/catalog
    restart: always
    ports:
      - 9000:8080

  customer:
    build: microservice-kubernetes-demo-customer/.
    container_name: customer
    image: rakesh635/customer
    restart: always
    ports:
      - 9000:8080

  hystrix-dashboard:
    build: microservice-kubernetes-demo-hystrix-dashboard/.
    image: rakesh635/dashboard
    restart: always
    ports:
      - 8989:8989

  order:
    build: microservice-kubernetes-demo-order/.
    container_name: order
    image: rakesh635/order
    restart: always
    ports:
      - 9000:8080
